apiVersion: v1
kind: Service
metadata:
  name: {{ include "webapp.fullname" . }}
spec:
  
  ports: 
  - port: {{ .Values.service.port}}
    targetPort: {{ .Values.service.target_port}}
    nodePort: 30008
 
    protocol: TCP
  sessionAffinity: {{ .Values.service.session_affinity}}
  selector:
    app: {{ include "webapp.fullname" . }}
    