apiVersion: v1
kind: Service
metadata:
  name: "sv1"
spec:
  type: "ClusterIP"
  ports: 
  - port: {{ .Values.service.port}}
    targetPort: {{ .Values.service.target_port}}
    
 
    protocol: TCP
  sessionAffinity: {{ .Values.service.session_affinity}}
  selector:
    app: {{ include "webapp.fullname" . }}
    