apiVersion: v1

kind: PersistentVolume

metadata:

  name: postgres-pv-volumestage

  labels:

   type: local

spec:

  storageClassName: local-path

  capacity:

   storage: 5Gi

  accessModes:

   - ReadWriteOnce

  hostPath:

   path: "/mnt/stage"