apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp-prod
  namespace: argocd
spec:
  project: default

  source:
    repoURL: git@github.com:babayaga-creator/webdeploy
    targetRevision: HEAD
    path: helm-chart/booking
  destination: 
    name: bizimkiler
    namespace: webapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true 
    automated:
      selfHeal: true
      prune: true
        