apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: booking
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:babayaga-creator/webdeploy
    targetRevision: main
    path: helm-chart/booking
  destination:
    server: https://kubernetes.default.svc
    namespace: webapp
  syncPolicy:
    automated: { }
    syncOptions:
    - CreateNamespace=true