---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: api-instances

resources:
  - ./postgress/templates/pv-volume.yml
  - ./postgress/templates/pv-claim.yml
  - ./postgress/templates/postgres-service.yml
  - ./postgress/templates/postgres-deployment.yml
  - ./webserver/templates/app-service.yml
  - ./webserver/templates/app-ingress.yaml 
  - ./webserver/templates/app-deployment.yml




